server:
  port: 9001
  servlet:
    context-path: /api


spring:
  application:
    name: api
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/api?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver

logging:
  config: classpath:api-logback.xml
  level:
    root: INFO
    com.wx: DEBUG
  path: ./logs
  name: api

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:Mapper/*.xml